### ISSUE TITLE
sources des PDF

### ISSUE THREAD

**Issue by trebmuh** [michelvergnaud/6PM#6]
Michel, j'ai repéré des petites erreurs dans le PDF en français. De plusse, j'aimerai pouvoir le modifier pour pouvoir faire une version avec des captures d'écran francisée pour ma petite LibraZiK. Du coup, si tu mettais les sources du pdf dans les sources générales de 6PM, ça serait super car je pourrais te corriger ces petites erreurs et je pourrais le rustiner pour LibraZiK .

Olivier

**Comment by michelvergnaud** [comment]
C'est fait, j'ai mis les fichiers .odt dans le dossier Doc

**Comment by trebmuh** [comment]
Super, voir mon commentaire : https://github.com/michelvergnaud/6PM/pull/10
