### ISSUE TITLE
[AMÉLIORATION] - Suggestion d'ajout d'une option en ligne de commande

### ISSUE THREAD

**Issue by trebmuh** [michelvergnaud/6PM#7]
Une pratique habituelle est de prévoir un retour pour les commandes :
- 6PM -h
- 6PM --help

Si tu fais cela, j'ajouterai ces options dans les pages de manuel.

**Comment by michelvergnaud** [comment]
Bien noté. Ça sera inclus dans la version 0.9 avec en plus  une option --nogui permettant de lancer le synthé sans interface. En préparation...

**Comment by trebmuh** [comment]
Super, encore mieux avec l'option --nogui, ça va plaire aux bidouilleurs et aux commandeurs-des-lignes !

**Comment by trebmuh** [comment]
Merci pour l'avoir intégré dans la version 0.9 :)
Je ferme cette demande.
